# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/jrm/git/pan_tilt_control_system/VHDL/PYNQ-Z2_v1.0.xdc

# Block Designs: bd/pwm_generator/pwm_generator.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pwm_generator || ORIG_REF_NAME==pwm_generator} -quiet] -quiet

# IP: bd/pwm_generator/ip/pwm_generator_xlconstant_0_0/pwm_generator_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pwm_generator_xlconstant_0_0 || ORIG_REF_NAME==pwm_generator_xlconstant_0_0} -quiet] -quiet

# IP: bd/pwm_generator/ip/pwm_generator_xlconstant_0_1/pwm_generator_xlconstant_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pwm_generator_xlconstant_0_1 || ORIG_REF_NAME==pwm_generator_xlconstant_0_1} -quiet] -quiet

# IP: bd/pwm_generator/ip/pwm_generator_counter_2_1/pwm_generator_counter_2_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pwm_generator_counter_2_1 || ORIG_REF_NAME==pwm_generator_counter_2_1} -quiet] -quiet

# IP: bd/pwm_generator/ip/pwm_generator_xlconstant_0_2/pwm_generator_xlconstant_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pwm_generator_xlconstant_0_2 || ORIG_REF_NAME==pwm_generator_xlconstant_0_2} -quiet] -quiet

# IP: bd/pwm_generator/ip/pwm_generator_reset_comparator_0_3/pwm_generator_reset_comparator_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pwm_generator_reset_comparator_0_3 || ORIG_REF_NAME==pwm_generator_reset_comparator_0_3} -quiet] -quiet

# IP: bd/pwm_generator/ip/pwm_generator_big_duty_cycle_lut_0_0/pwm_generator_big_duty_cycle_lut_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pwm_generator_big_duty_cycle_lut_0_0 || ORIG_REF_NAME==pwm_generator_big_duty_cycle_lut_0_0} -quiet] -quiet

# IP: bd/pwm_generator/ip/pwm_generator_comparator_1_1/pwm_generator_comparator_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pwm_generator_comparator_1_1 || ORIG_REF_NAME==pwm_generator_comparator_1_1} -quiet] -quiet

# IP: bd/pwm_generator/ip/pwm_generator_big_duty_cycle_lut_0_1/pwm_generator_big_duty_cycle_lut_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pwm_generator_big_duty_cycle_lut_0_1 || ORIG_REF_NAME==pwm_generator_big_duty_cycle_lut_0_1} -quiet] -quiet

# IP: bd/pwm_generator/ip/pwm_generator_clear_comparator_1_0/pwm_generator_clear_comparator_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pwm_generator_clear_comparator_1_0 || ORIG_REF_NAME==pwm_generator_clear_comparator_1_0} -quiet] -quiet

# IP: bd/pwm_generator/ip/pwm_generator_comparator_3_0/pwm_generator_comparator_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pwm_generator_comparator_3_0 || ORIG_REF_NAME==pwm_generator_comparator_3_0} -quiet] -quiet

# IP: bd/pwm_generator/ip/pwm_generator_disabled_0_0/pwm_generator_disabled_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pwm_generator_disabled_0_0 || ORIG_REF_NAME==pwm_generator_disabled_0_0} -quiet] -quiet

# IP: bd/pwm_generator/ip/pwm_generator_enabled_0_0/pwm_generator_enabled_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pwm_generator_enabled_0_0 || ORIG_REF_NAME==pwm_generator_enabled_0_0} -quiet] -quiet

# IP: bd/pwm_generator/ip/pwm_generator_twentyone_constant_0_0/pwm_generator_twentyone_constant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pwm_generator_twentyone_constant_0_0 || ORIG_REF_NAME==pwm_generator_twentyone_constant_0_0} -quiet] -quiet

# IP: bd/pwm_generator/ip/pwm_generator_twentyone_counter_0_0/pwm_generator_twentyone_counter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pwm_generator_twentyone_counter_0_0 || ORIG_REF_NAME==pwm_generator_twentyone_counter_0_0} -quiet] -quiet

# IP: bd/pwm_generator/ip/pwm_generator_xlslice_0_0/pwm_generator_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pwm_generator_xlslice_0_0 || ORIG_REF_NAME==pwm_generator_xlslice_0_0} -quiet] -quiet

# IP: bd/pwm_generator/ip/pwm_generator_clk_divider_0_0/pwm_generator_clk_divider_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pwm_generator_clk_divider_0_0 || ORIG_REF_NAME==pwm_generator_clk_divider_0_0} -quiet] -quiet

# IP: bd/pwm_generator/ip/pwm_generator_pwm_soft_start_0_0/pwm_generator_pwm_soft_start_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pwm_generator_pwm_soft_start_0_0 || ORIG_REF_NAME==pwm_generator_pwm_soft_start_0_0} -quiet] -quiet

# XDC: /home/jrm/git/pan_tilt_control_system/VHDL/pwm_generator/pwm_generator.gen/sources_1/bd/pwm_generator/pwm_generator_ooc.xdc
